### ISSUE TITLE
ERP next intergration with Magento

### ISSUE THREAD

**Issue by prash4** [openlabs/magento#26]
Hello,

We are  an ecommerce company , we need to integrate it with Erp Next , how can we do it ?

**Comment by raimonesteve** [comment]
Hie prash4,

to integrate with ERPNext, you need to ask to ERPNext project or community.

This project "magento" (1) is a library to connect Magento to app written in Python, for example, Tryton.

Regards.

(1) https://pypi.python.org/pypi/magento

**Comment by rphce3** [comment]
Hi Prash4,

You can use this api to build something on your own, but if you are interested in getting a commercial bid for the same write to hello@openlabs.co.in

Regards
Rohit

**Comment by MarySmith13** [comment]
Hi, I think you'd better to ask another experienced ecommerce company working on magento. For example http://magecom.net/  I suppose the have already coped with problems like this.
